### ISSUE TITLE
Typo in installation guide

### ISSUE THREAD

**Issue by jgoedde** [joni1802/ts3-manager#110]
Hey, I am using this tool and ran it using the docker-compose file provided in the installation section on the [docs](https://www.ts3.app/guide/installation.html#compose-file-example).

The service there is named _ts3-manger_ instead of _ts3-manager_

I know, I know, it's just an example file, but still... :laughing: 

![image](https://github.com/joni1802/ts3-manager/assets/129423545/0019c4ea-8c1b-4a94-a871-18bd6ce99ab1)

**Comment by joni1802** [comment]
Oh yeah. Fixed it. Thanks.
