### ISSUE TITLE
Edit Servergroup

### ISSUE THREAD

**Issue by mythfx** [joni1802/ts3-manager#27]
Hi,
it's not possible to add / remove Users in the Edit Servergroup Dialog url/servergroup/id/edit
Only get the ui message
![image](https://user-images.githubusercontent.com/4218537/103460913-99d08480-4d1a-11eb-96d9-2f690816d7e1.png)

Thanks.

**Comment by joni1802** [comment]
Hello,

sorry but I cannot reproduce the error (tested on server version 3.12.1 and 3.13.3). In the error.log file should be more informations about the error. Can you please provide the error.log.

**Comment by mythfx** [comment]
Hi,

I'm using the 3.13.3 docker version with a mysql backend.

There's no entry in the error.log:
![image](https://user-images.githubusercontent.com/4218537/103462104-4dd60d80-4d23-11eb-85a5-fe2c6ebcdaf7.png)

Also nothing interesting in the normal log:
`2021-01-02 17:00:13 | 79.196.86.17 | INFO | servergroupclientlist -names sgid=17`
`2021-01-02 17:00:20 | 79.196.86.17 | INFO | servergrouprename sgid=17 name=test`
`2021-01-02 17:00:20 | 79.196.86.17 | INFO | servergrouplist`


Here are all websocket messages
`4220["teamspeak-execute",{"command":"servergrouprename","params":{"sgid":17,"name":"test"},"options":[]}]`

`4320[{"message":"database no modifications","id":1283,"connected":true}]`

`4221["teamspeak-execute",{"command":"servergrouplist","params":{},"options":[]}]`

`4321[[{"sgid":1,"name":"Guest Server Query","type":2,"iconid":0,"savedb":0,"sortid":0,"namemode":0,"n_modifyp":100,"n_member_addp":0,"n_member_removep":0},{"sgid":2,"name":"Admin Server Query","type":2,"iconid":500,"savedb":1,"sortid":0,"namemode":0,"n_modifyp":100,"n_member_addp":100,"n_member_removep":100},{"sgid":3,"name":"Server Admin","type":0,"iconid":300,"savedb":1,"sortid":0,"namemode":0,"n_modifyp":75,"n_member_addp":75,"n_member_removep":75},{"sgid":4,"name":"Normal","type":0,"iconid":0,"savedb":1,"sortid":0,"namemode":0,"n_modifyp":75,"n_member_addp":60,"n_member_removep":60},{"sgid":5,"name":"Guest","type":0,"iconid":0,"savedb":0,"sortid":0,"namemode":0,"n_modifyp":75,"n_member_addp":0,"n_member_removep":0},{"sgid":6,"name":"Server Admin","type":1,"iconid":405387246,"savedb":1,"sortid":1,"namemode":0,"n_modifyp":75,"n_member_addp":75,"n_member_removep":75},{"sgid":7,"name":"Normal","type":1,"iconid":1082748225,"savedb":1,"sortid":0,"namemode":0,"n_modifyp":75,"n_member_addp":40,"n_member_removep":60},{"sgid":8,"name":"Guest","type":1,"iconid":1237766804,"savedb":0,"sortid":0,"namemode":0,"n_modifyp":75,"n_member_addp":0,"n_member_removep":0},{"sgid":17,"name":"test","type":1,"iconid":0,"savedb":1,"sortid":0,"namemode":0,"n_modifyp":100,"n_member_addp":100,"n_member_removep":100}]]`

`4222["teamspeak-execute",{"command":"clientdblist","params":{"start":0,"duration":200},"options":[]}]`

`4222 ... huge client list...`

`4223["teamspeak-execute",{"command":"clientdblist","params":{"start":0,"duration":200},"options":[]}]`

`4223 ... huge client list...`

`4224["teamspeak-execute",{"command":"clientdblist","params":{"start":200,"duration":400},"options":[]}]`

`4324[{"message":"database empty result set","id":1281,"connected":true}]`

**Comment by joni1802** [comment]
Ok. I created a new issue for the missing error logs. (See #28) 

When you try to add a user to a group is there some log message like this ``servergroupaddclient  sgid=X cldbid=X`` in the combined.log file?

**Comment by mythfx** [comment]
No, there are only two entries:
`2021-01-02 17:50:01 | 79.196.86.17 | INFO | servergrouprename sgid=17 name=test`
`2021-01-02 17:50:01 | 79.196.86.17 | INFO | servergrouplist`

Could it be a similar issue like https://github.com/joni1802/ts3-manager/issues/26 because there are users with a pipe symbol in the name?

**Comment by mythfx** [comment]
Hi, just created two fresh teamspeak servers.
First one with a sqlitedb - working
Second with a mysql database - not working

**Comment by joni1802** [comment]
I have tested it with the mariadb database now and came to the same result like you. 
With sqlite it works without a problem. With mariadb/mysql the error "database no modifications" is thrown by the ServerQuery. 

Here is the reason why it happens:
When you hit "apply" on the server group edit page the TS3-Manager always sends the command ``servergrouprename`` with the current value in the html form to the Teamspeak ServerQuery. Even though the name of the group got not changed. And here is the problem. For any reasons the mariadb/mysql version of TeamSpeak does not like to set the same name to the server group again. So if you did not have changed the name of the group and just edited the group members, it results in this error and the next commands to changed the group members will not be send to the ServerQuery. 

So it is more an error by the database of TeamSpeak. But I can easily fix it in the TS3 Manager, so only the command ``servergrouprename`` is send when the name got really changed. 

I will publish a new release maybe next week with all the fixes.

**Comment by joni1802** [comment]
Got fixed. See 246760879b4003f3b2f4b8a4be16b7254e8399e6
