### ISSUE TITLE
[Linux version] Can't connect (other querry port)...

### ISSUE THREAD

**Issue by FreakyMan82** [joni1802/ts3-manager#3]
Hi!
I just tested your manager and i can't connect.
I use other ts querry port and it seems that he try to connect to the default one (10011)!
Attached you have the screens.

P.S.: Sorry but i blurred my ip's, ts and personal!

![ts3manager2](https://user-images.githubusercontent.com/29159355/70128777-2aefaa80-1686-11ea-93d3-25ef126f8db8.png)
![ts3manager](https://user-images.githubusercontent.com/29159355/70128794-3347e580-1686-11ea-9b42-6f72b52ab491.png)

**Comment by joni1802** [comment]
Hello,

it is a bug. It always tries to fallback to the default port 10011. This weekend there will be a new version with a fix and some new features.

Right now there is no workaround for that. Sorry.

**Comment by joni1802** [comment]
The newest fixed version can be now downloaded on sourceforge.

**Comment by joni1802** [comment]
[Download Link](https://sourceforge.net/projects/ts3-manager/files/)
