### ISSUE TITLE
TS3 Manager on my website

### ISSUE THREAD

**Issue by TS3Joke** [joni1802/ts3-manager#36]
Hello, I would like to install it directly on TS3 Manager on my website but I cannot find a solution can you enlighten me if this is possible

**Comment by joni1802** [comment]
If I understand you correctly, you want to install it on a hosted webserver where you have no root access to the underlying system. This is not possible. The TS3 Manager is written in NodeJS so it will not run on a standard Apache webserver which only supports PHP for example. You need to have access to a machine with full access to be able to run the TS3 Manager. Something like a hosted VPS.
