### ISSUE TITLE
Ability to manage channels

### ISSUE THREAD

**Issue by EinDev** [joni1802/ts3-manager#39]
This is just an idea, but shouldn't there be a way to manage channels using serverquery?
I think a "channel designer" with some easy-to-use presets would be a great addition on this manager.

Of course there are some special designs, but most of the time when i met people wanting to set up TeamSpeak-Servers such an addition would have helped them a lot.

Features (maybe someone got something to add)
- Spacer design presets
- Spacer preview (with respect to centered, left, right)
- Bulk channel (spacer) creation (I imagine a text editor, where each line is a channel)
- Temporary by default (should be already default if using serverquery, right?)
- Automatic name collision detection (automaticially assign spacer numbers)
- Spacer number ordering (Assign spacer numbers in order, so when channels are accidentally moved, their original position can be retrieved by the number)

**Comment by joni1802** [comment]
Hey, your feature request for a channel designer sounds interesting. But I think a "channel designer" is a little bit to much. I think a seperate page for creating spacer channels will fit better. So for example in the Server Viewer would be a specific option to add spacer channels. I will try to consider some of the requests you have a listed (preview, name collision detection etc...).

> Of course there are some special designs, but most of the time when i met people wanting to set up TeamSpeak-Servers such an addition would have helped them a lot.
> [...] Spacer design presets

There are already websites for that. For example [https://ts3index.com/?page=generator](https://ts3index.com/?page=generator). I think a tooltip with a short description for the syntax of spacers like in the Teamspeak 3 Client should be enough. 

> Bulk channel (spacer) creation (I imagine a text editor, where each line is a channel)

*No answer. Have to think about that 🤔

> Temporary by default (should be already default if using serverquery, right?)

It is already temporary by default.

**Comment by joni1802** [comment]
In the [new release v2.1.0](https://github.com/joni1802/ts3-manager/releases/tag/v2.1.0) is a new feature where you can add special spacer channels. The feature can be found in the Server Viewer. There are now two options available to add new channels. One for a normal channel and one for a spacer channel.
