### ISSUE TITLE
Insufficient client permissions, failed on permid 3

### ISSUE THREAD

**Issue by Limoniak** [joni1802/ts3-manager#45]
Hello, thank you for your work!

When I connect to the interface I get the message "insufficient client permissions, failed on permid 3"

ts3-manager on Docker

[_ts3-manager_logs.txt](https://github.com/joni1802/ts3-manager/files/6503261/_ts3-manager_logs.txt)

**Comment by joni1802** [comment]
This is not really an error from the TS3 Manager. You have not enough permissions on the TeamSpeak server with the account you used to login. You will see the same results if you login directly via SSH or Telnet to the ServerQuery of your server. So I cannot really help you with this problem. Maybe a reset of the serveradmin password will help.

**Comment by Limoniak** [comment]
it's ok it's me sorry.. ^^
