### ISSUE TITLE
read ECONNRESET

### ISSUE THREAD

**Issue by Hoffi-Flex** [joni1802/ts3-manager#50]
Hey,

I have an issue with your otherwise great webinterface.
After logging in and out of the server query a few times I am unable to log back in and constantly get the Error "read ECONNRESET". In order to resolve this issue I have to restart the Teamspeak server itself.
You have to change the file type of the logs to .html for proper display.

Thank you for your awesome Webinterface.

[ts3-manager.txt](https://github.com/joni1802/ts3-manager/files/6616345/ts3-manager.txt)

**Comment by joni1802** [comment]
Hello,

Looks like a problem with the flooding protection of the TeamSpeak Server. Which TeamSpeak Server version are you using?

**Comment by Hoffi-Flex** [comment]
Hi,

I am using 3.13.5

**Comment by joni1802** [comment]
There is known bug with this version. A lot of other 3rd party tools are having the same problems. The TeamSpeak team released a new version 3.13.6-experimental a week ago. This version should fix the issue. 

See [https://community.teamspeak.com/t/latest-server-update-3-13-5-broke-gametracker-and-servers-board/22691](https://community.teamspeak.com/t/latest-server-update-3-13-5-broke-gametracker-and-servers-board/22691)

**Comment by Hoffi-Flex** [comment]
Ok, I will just wait for the release and hope that it fixes the bug.

Thank you very much for your help :D

**Comment by joni1802** [comment]
As a workaround you can add the IP address of the TS3 Manager to the TeamSpeak whitelist. In the next version of the TS3 Manager this will be required anyways.
