### ISSUE TITLE
insufficient client permissions & invalid serverID

### ISSUE THREAD

**Issue by FoxModsTM** [joni1802/ts3-manager#54]
Hey,

I receive these errors and I don't know why.
I am not that great with this type of teamspeak work sorry.

LOG:
[error.log](https://github.com/joni1802/ts3-manager/files/6681691/error.log)

If someone could explain what this means and how to fix it please do!

**Comment by joni1802** [comment]
Hello,

the user account you are using has not enough permissions to select the server. Make sure you are using the serveradmin.

**Comment by EinKantHolz** [comment]
lol. same problem, I am the admin of my own server.
