### ISSUE TITLE
[feature request] Option to auto-fill server ip/domain

### ISSUE THREAD

**Issue by cleanlock** [joni1802/ts3-manager#56]
Hello,

would it be possible to add an option so server ip/domain will be auto-filled?

That'd be dope. Thanks

**Comment by joni1802** [comment]
Hello,

there already is. 
![Bild_2021-07-17_135930](https://user-images.githubusercontent.com/40319156/126036114-04da5a09-5ba2-4d70-baf7-23ee09192526.png)

**Comment by cleanlock** [comment]
I just recompiled the project and pre-filled the "host" field since I host it on the same system as the teamspeak server. 

The "remember me" option doesn't fulfill what I wanted.

**Comment by joni1802** [comment]
You want the server IP or domain is prefilled by default. I think the current solution should be enough and is a little bit better in terms of security.

**Comment by cleanlock** [comment]
Well, I wanted it pre-filled with 127.0.0.1 by default which I did by editing the Login.vue file. I've set `host: "127.0.0.1"`. Afterwards I just re-packed/compiled the app. Works like charm.
