### ISSUE TITLE
cant run on raspberry pi

### ISSUE THREAD

**Issue by crazytechkid** [joni1802/ts3-manager#57]
I am trying to run this on ubuntu server which is running on my raspberry pi but I keep getting the error `exec user process caused: exec format error` any ideas?

**Comment by joni1802** [comment]
The executable file only supports x86/x64 architekture. But you can build your own executable file and run it on your raspberry pi by following this guide:
[https://www.ts3.app/guide/Advanced.html#compile-your-own-executable](https://www.ts3.app/guide/Advanced.html#compile-your-own-executable)

**Comment by joni1802** [comment]
There is now an official docker image of the TS3-Manager for the Raspberry Pi available. 
Rel. #62
