### ISSUE TITLE
Frontend/Backend

### ISSUE THREAD

**Issue by Justman10000** [joni1802/ts3-manager#58]
Where are the associated folders?

**Comment by joni1802** [comment]
With the last release I switched to npm workspaces. This is the reason why the structured changed. The code of the frontend is now placed under /packages/ui and for the backend under /packages/server.
Now it is much easier to spin up the dev environment. You simply need to run `npm run dev`.

**Comment by Justman10000** [comment]
> 
> 
> With the last release I switched to npm workspaces. This is the reason why the directory structure changed. The code of the frontend is now placed under /packages/ui and for the backend under /packages/server.
> Now it is much easier to spin up the dev environment. You simply need to run `npm run dev`.

But then I would update the documentation:

![grafik](https://user-images.githubusercontent.com/49990629/132394199-0f0227da-28fa-4c2b-bf3a-c94f4f2192f7.png)

**Comment by Justman10000** [comment]
The script serve supposedly does not exist:

![grafik](https://user-images.githubusercontent.com/49990629/132394396-ca5d5807-2ad7-48a7-857f-d9d3f3108ca1.png)

**Comment by Justman10000** [comment]
> 
> 
> The script serve supposedly does not exist:
> 
> ![grafik](https://user-images.githubusercontent.com/49990629/132394396-ca5d5807-2ad7-48a7-857f-d9d3f3108ca1.png)

What is also called with `npm run dev`...

**Comment by joni1802** [comment]
You need at least npm version 7 installed and make sure you have run `npm install` in the root directory before running `npm run dev`. Also set the environment variable NODE_ENV to development to avoid CORS errors by creating a .env file in the server directory.

**Comment by Justman10000** [comment]
> 
> 
> You need at least npm version 7 installed and make sure you have run `npm install` in the root directory before running `npm run dev`. Also set the environment variable NODE_ENV to development to avoid CORS errors by creating a .env file in the server directory.

Strange, after installing the latest versions, npm was actually only on version 6, it works!

**Comment by Justman10000** [comment]
Would it still be possible to introduce [i18n](https://kazupon.github.io/vue-i18n)?

**Comment by joni1802** [comment]
Would be possible but a lot of work. It is not on my list currently.

**Comment by Justman10000** [comment]
Well, that would be really nice! I would then be responsible for the German translation!

**Comment by joni1802** [comment]
Updated the documentation for developers and how to create the executable file. 
- [https://www.ts3.app/guide/developers.html](https://www.ts3.app/guide/developers.html)
- [https://www.ts3.app/guide/advanced.html#compile-your-own-executable](https://www.ts3.app/guide/advanced.html#compile-your-own-executable)
