### ISSUE TITLE
Cannot follow guide

### ISSUE THREAD

**Issue by qualk** [joni1802/ts3-manager#59]
Hello, I cannot run the command `sudo adduser --system --no-create-home --group --disabled-password ts3-manager` in Arch Linux, as `adduser` is not a valid command. What is the equivalent command (I looked on Stack Exchange and stuff, but I want to make sure)?

**Comment by Justman10000** [comment]
> 
> 
> Hello, I cannot run the command `sudo adduser --system --no-create-home --group --disabled-password ts3-manager` in Arch Linux, as `adduser` is not a valid command. What is the equivalent command (I looked on Stack Exchange and stuff, but I want to make sure)?

It is also not absolutely necessary! You can also run the panel via root...

**Comment by joni1802** [comment]
I think Arch Linux  only supports `useradd`. Take a look at the [ArchWiki > User Management](https://wiki.archlinux.org/title/users_and_groups) for more details. 

> It is also not absolutely necessary! You can also run the panel via root...

True. But as already mentioned in the documentation it is more secure to run it under a different user with less permissions.

**Comment by Justman10000** [comment]
> 
> 
> I think Arch Linux only supports `useradd`. Take a look at the [ArchWiki > User Management](https://wiki.archlinux.org/title/users_and_groups) for more details.
> 
> > It is also not absolutely necessary! You can also run the panel via root...
> 
> True. But as already mentioned in the documentation it is more secure to run it under a different user with less permissions.

Hmm, I thought to myself 😂!
