### ISSUE TITLE
Raspberry Pi package  

### ISSUE THREAD

**Issue by lastsamurai26** [joni1802/ts3-manager#64]
Is there a way to provide a package for raspberry Pi? 
As you know, the Pi's only have 1 GB of RAM, which makes it impossible to build a package.

**Comment by joni1802** [comment]
Currently the only way to run it on a Raspberry Pi is to run it in a container by using the official Docker image. But I am also working on a solution to provide the raw executable file for ARM. There a still some problems to automate it though.

**Comment by lastsamurai26** [comment]
that sounds great

**Comment by lastsamurai26** [comment]
Doesn't really belong to this topic, but do you know a way to change a reverse proxy so that a subfolder serves as the URL?


I would like to do the following 
domain.com/ts3-manager
 
use http and https as URL, but unfortunately I can't really do that, I only manage to reverse one domain

**Comment by joni1802** [comment]
This question got already asked. See #44.
> So if you really want to change the base path, you have to set it before the build process and build the frontend on your own.
https://cli.vuejs.org/config/#publicpath
