### ISSUE TITLE
How can i get serveradmin password and connect?

### ISSUE THREAD

**Issue by Jotasct** [joni1802/ts3-manager#65]
How can i get serveradmin password and connect?

I cant get it! ^^

Thx in advance.

**Comment by joni1802** [comment]
When you have started your teamspeak server at the first time your privlege key and the password of the serveradmin is shown. 
Here is a guide how to reset the password:
[https://support.teamspeak.com/hc/en-us/articles/360002712898-How-do-I-change-or-reset-the-password-of-the-serveradmin-Server-Query-account-](https://support.teamspeak.com/hc/en-us/articles/360002712898-How-do-I-change-or-reset-the-password-of-the-serveradmin-Server-Query-account-)
