### ISSUE TITLE
Failed the Handshake

### ISSUE THREAD

**Issue by spkesDE** [joni1802/ts3-manager#66]
Hey,

I'm running the ts3-manager in a docker image via pterodactyl.
The TeamSpeak 3 server runs also over a docker image also via pterodactyl.

But somehow I can't connect via ts3-manager to the query.
```
2022-01-16 15:30:01 | ERROR | Socket Timeout reached
2022-01-16 15:30:34 | ERROR | Timed out while waiting for handshake
```
But I can connect fine via putty/telnet

**Comment by joni1802** [comment]
This error means that the selected network port is not reachable. Did you also published the SSH port (10022) of your TeamSpeak Docker container? 
If only the Telnet port (10011) of the TeamSpeak container is opened, you have to uncheck "SSH".
![image](https://user-images.githubusercontent.com/40319156/149668029-5c815508-2ba8-41a7-9f92-c39004acf956.png)

**Comment by spkesDE** [comment]
Yeah my teamspeak has all needed ports open. Even when I uncheck the SSH I get an error. 
```
container@pterodactyl~ Server marked as running...
2022-01-16 16:30:18 | INFO | Socket.io connected
2022-01-16 16:30:38 | ERROR | Socket Timeout reached
```

**Comment by joni1802** [comment]
Sorry but I can't help you with that. This is not an error of the TS3 Manager. Maybe there are some outgoing firewall rules or maybe the IP Address of the TS3 Manager got blacklisted by the TeamSpeak server.
