### ISSUE TITLE
SRV support

### ISSUE THREAD

**Issue by cpjet64** [joni1802/ts3-manager#68]
Would it be possible to get SRV DNS support? Using a subdomain would be amazing!

**Comment by joni1802** [comment]
Hello,

just use a reverse proxy for this. 
I have already posted example configuration files for NGINX and Apache.
Take a look here:
[https://www.ts3.app/guide/advanced.html#Reverse-Proxy](https://www.ts3.app/guide/advanced.html#Reverse-Proxy)

Jonathan
