### ISSUE TITLE
Make Guest ServerQuery only see its own server

### ISSUE THREAD

**Issue by cleanlock** [joni1802/ts3-manager#71]
Hi,

at the moment, Guest ServerQuery can see all servers. That's not really good imo. Guest ServerQuery-Accounts should only see their own server, but not any other (due to privacy etc.).

**Comment by joni1802** [comment]
This is a permission issue on the TeamSpeak server itself and not handled by the TS3 Manager. You have to set the correct permissions for that on the TeamSpeak server. The TS3 Manager is only the frontend and only uses the user account you signed in to send data to the ServerQuery.

**Comment by cleanlock** [comment]
Well, it's actually not a permission issue... either a Guest ServerQuery can see the whole serverlist or nothing and I end up getting permid 3 error.

If I add the permission "b_serverinstance_virtualserver_list", all servers are visible. There seems to be nothing in between. 

If I'm wrong and it's a permission issue, I'd like to know how I can set it up properly, so this doesn't happen.

**Comment by joni1802** [comment]
Can you please explain the problem in more detail. How do the Guest actually logs into the TS3 Manager? As far as I know, it is not possible to add multiple ServerQuery accounts for the ServerQuery login over SSH. It is only possible to use the serveradmin with the password. The login as a guest without a password is only possible when you are still using the old ServerQuery over Telnet. The TS3 Manager still supports the login over Telnet but only as a serveradmin with a password. So I do not quite understand how you actually  did login into it with a guest user and the see the server list.

**Comment by cleanlock** [comment]
serveradmin = Admin Server Query
Accounts created on a TeamSpeak Server by a Server Admin = Guest Server Query.

With the Webinterface by Psychokiller, Guest Server Query accounts can only see the server on which the account has been created. So I guess, it must be possible to identify the serverid of the Guest Server Query accounts and therefore only show the server they've been created on.
