### ISSUE TITLE
[REQUEST] UI login + Save data

### ISSUE THREAD

**Issue by ITKewai** [joni1802/ts3-manager#75]
![image](https://user-images.githubusercontent.com/44037081/189731824-e4238ec8-eda2-4fdb-93bc-301fe301a415.png)
Add an option to enable  save login data to a container so you can easily manage different server

**Comment by joni1802** [comment]
Hello,

your request looks interesting. But honestly I am not a big fan of it. Also the better solution for hosting multiple TeamSpeak servers is by running one instance with multiple virtual servers. So you would have still only one login for managing all instances. I know you need a license for that but this is the official way provided by TeamSpeak.

**Comment by ITKewai** [comment]
> Hello,
> 
> your request looks interesting. But honestly I am not a big fan of it. Also the better solution for hosting multiple TeamSpeak servers is by running one instance with multiple virtual servers. So you would have still only one login for managing all instances. I know you need a license for that but this is the official way provided by TeamSpeak. 

Yeah, the issue is that I manage 3 different license for different people so each have vserver too their own...
Btw is just an idea; for my lazinesz i think I will try to run different node server on different port 🙃
