### ISSUE TITLE
TeamSpeak on AWS

### ISSUE THREAD

**Issue by agamerj** [joni1802/ts3-manager#8]
Hello, I run TeamSpeak on AWS which runs on Key instead of Password.

How am I suppose to connect TeamSpeak Manager with the AWS?

Please guide.

Thanks.

**Comment by joni1802** [comment]
I assume that you are using an EC2 instance and running the TeamSpeak Server on an Ubuntu machine. So there should be no difference. Just login with the serveradmin and the password. 
Do not confuse the SSH connection to your Ubuntu machine (default Port 22) with the SSH connection to your TeamSpeak ServerQuery (default Port 10022).

Did you already tried to login to the TeamSpeak ServerQuery directly over a terminal appplication? If this works, the login should also work in the TS3 Manager.

**Comment by agamerj** [comment]
Yeah, I am actually using Lightsail (AWS' alternative to DigitalOcean).

Yes, I am using Ubuntu 16 for this.

Problem is that, Yes, I have installed the TeamSpeak 3 on it.

But, I am unable to know what's my ServerQuery Password is.

It doesn't show up when I install the server either.

How do I know what's my ServerQuery Password?

Also, Do you have any kind of Telegram Group or Discord Server?

Thanks.

**Comment by joni1802** [comment]
You can take a look at the logs. (First red square in the screenshot)
![serverquery image](https://goneuland.de/wp-content/uploads/2020/03/Teamspeak3-Docker-001-1.png)
Or you can just reset the password over SSH. Take a look here:
[https://support.teamspeak.com/hc/en-us/articles/360002712898-How-do-I-change-or-reset-the-password-of-the-serveradmin-Server-Query-account-](https://support.teamspeak.com/hc/en-us/articles/360002712898-How-do-I-change-or-reset-the-password-of-the-serveradmin-Server-Query-account-)

> Also, Do you have any kind of Telegram Group or Discord Server?

No, you can post your questions here on github or on [reddit](https://www.reddit.com/r/teamspeak3/comments/fw7476/teamspeak_3_open_source_webinterface_for/)

**Comment by agamerj** [comment]
I'm sorry to ask but how do you check the logs?

Because, the results on google are a lot outdated.

**Comment by joni1802** [comment]
The logs are in the log directory of your TeamSpeak server folder. But I am not 100% sure if the credential are really stored inside the logs. I guess the easiest way is resetting the password.

**Comment by agamerj** [comment]
Please if you could check am I at the right place?

Because none of those logs had the query admin/password.

![sx-21-May-20-4597](https://user-images.githubusercontent.com/9323342/82492287-92e66000-9b03-11ea-8fce-694efc118746.png)

**Comment by joni1802** [comment]
Yeah you are in the correct directory. I guess I was wrong with the logs and the login credentials.

**Comment by agamerj** [comment]
What OS do you use for your Linux TS Server?

Is that CentOS?

**Comment by joni1802** [comment]
> What OS do you use for your Linux TS Server?

I am using the official docker image of TeamSpeak.

> Also, How did you get this then if you're wrong?

... on the internet my friend 😎.

**Comment by agamerj** [comment]
Any benefit of using Docket over the manual way of installing TS?

**Comment by joni1802** [comment]
Some of the benefits when using docker are:
- easier to install
- easier to maintain (e.g updating to newer versions)
- more secure

Docker is awesome 🐳. If you want to learn docker I recommend reading the official docs [https://docs.docker.com/get-started/](https://docs.docker.com/get-started/)
