### ISSUE TITLE
Provide shaXsums for binary downloads

### ISSUE THREAD

**Issue by dionysius** [joni1802/ts3-manager#9]
Downloaded executable https://sourceforge.net/projects/ts3-manager/files/ts3-manager-linux-v1.6.0/download but I get greeted with v1.5.1 in the login screen and get an update notification after I'm logged in.

sha256sum of the executable: 879d1da199c9ee6ba2abca0bb3ab7f1bf775764f6e0bbeb9634915aa1e37cb5c

![image](https://user-images.githubusercontent.com/1341084/83557098-55290480-a511-11ea-8d65-c7c729c8c642.png)

![image](https://user-images.githubusercontent.com/1341084/83557157-72f66980-a511-11ea-995a-5a28bc893fc3.png)

Additionally: can you provide shasums so we can verify the file/download hasn't been tampered?

**Comment by joni1802** [comment]
Yes, you are right. There was the wrong version for the linux executable on sourceforge. I have updated all packages on sourceforge on **version 1.6.1**.

Download here: https://sourceforge.net/projects/ts3-manager/

> can you provide shasums so we can verify the file/download hasn't been tampered?

I will add this to my to-do list.

**Comment by dionysius** [comment]
Thank you, gonna try the latest download soon. I've updated the title to easier find that todo :) Thank you for that nice manager!

**Comment by joni1802** [comment]
Added table with the md5 and sha1 hashes on [https://www.ts3.app/download/#checksums](https://www.ts3.app/download/#checksums).
